setup(
    name="elementify",
    version="1.1.0",
    description="A simple program that gives you information about chemical elements when you search them",
    long_description=README,
    long_description_content_type="text/markdown",
    url="https://github.com/shibaismyname/elementify",
    author="shibaismyname",
    author_email="robertozunica69@gmail.com",
    license="MIT",
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
    ],
    packages=["reader"],
    include_package_data=True,
    install_requires=["pandas"],
    entry_points={},
)
